---
layout: main
title: "Ops for Developers: Because I can't bring myself to use the term 'DevOps'"
---

## Ops for Developers

* [Slides](output/index.html)

* [Source](https://github.com/goozbach-presentation/ops-for-developers)



